name: rst
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc_linux-64
  - cython
  - python=3.7
  - cythongsl
  - gsl
  - h5py
  - numpy
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - mock
  - pillow
  - pip
  - pip:
    - recommonmark
    - readthedocs-sphinx-ext