name: rst
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc_linux-64
  - cython
  - python=3.7
  - gsl
  - llvm-openmp
  - fftw
  - h5py
  - numpy
  - scipy
  - sphinx
  - furo
  - sphinx-autodoc-typehints
  - mock
  - pillow
  - tqdm